before:
  hooks:
  - go mod download

# Build customization
builds:
  - binary: datadog-terraformer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/kterada0509/datadog-terraformer/internal.version={{.Tag}} -X github.com/kterada0509/datadog-terraformer/internal.date={{.Date}}

# Archive customization
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip

# Release customization
release:
  github:
    owner: kterada0509
    name: datadog-terraformer

brew:
  github:
    owner: kterada0509
    name: homebrew-tap

  url_template: "https://github.com/kterada0509/datadog-terraformer/releases/download/{{ .Tag }}/datadog-terraformer_{{ .Version }}_darwin_amd64.tar.gz"

  homepage: "https://github.com/kterada0509/datadog-terraformer"

  description: Command Line Tool for exporting existing Datadog resources to HCL

  skip_upload: false

  test: |
    system "#{bin}/datadog-terraformer --version"

  install: |
    bin.install "datadog-terraformer"
