before:
  hooks:
  - go mod download

# Build customization
builds:
  - binary: datadog-terraformer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/kterada0509/datadog-terraformer/internal.version={{.Tag}} -X github.com/kterada0509/datadog-terraformer/internal.date={{.Date}}

# Archive customization
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip

# Release customization
release:
  github:
    owner: kterada0509
    name: datadog-terraformer

#brew:
#  github:
#    owner: kterada0509
#    name: homebrew-datadog-terraformer
#
#  homepage: "https://github.com/kterada0509/datadog-terraformer"
#
#  install: |
#    bin.install "datadog-terraformer"