dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.11.1

env:
- GO111MODULE=on

install:
  - make setup

script:
  - if test -z "$TRAVIS_TAG"; then make fmtcheck; fi
  - if test -z "$TRAVIS_TAG"; then make errcheck; fi

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux