dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.11.1

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - test "$TRAVIS_TAG" && make fmtcheck
  - test "$TRAVIS_TAG" && make errcheck

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash