dist: xenial
sudo: required
services:
  - docker
language: go
go:
  - "1.12.x"
env: GOFLAGS=-mod=vendor

git:
  depth: 1

install:
  - make tools

script:
  - if [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make lint; fi
  - if [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make test; fi
  - if [ "$TRAVIS_BRANCH" = "master"] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make lint; fi
  - if [ "$TRAVIS_BRANCH" = "master"] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make test; fi

branches:
  only:
    - master

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux