dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.11.1

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - test "$TRAVIS_TAG" && make fmtcheck
  - test "$TRAVIS_TAG" && make errcheck

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux