dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.11.1

install:
  - make setup

script:
  - test "$TRAVIS_TAG" && make fmtcheck
  - test "$TRAVIS_TAG" && make errcheck

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script:
    - curl -sL https://git.io/goreleaser | bash
    - git diff go.mod
    - git diff go.sum
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux